### ISSUE TITLE
Cannot attack people when using SmashHit on my server

### ISSUE THREAD

**Issue by flapppie1** [Speentie8081/SmashHit#2]
i got it to work but it doesnt let me hit people, could it be my plugins? or could it be my server (it runs at 1.7 x 1.8)

some help would be appreciated

**Comment by Speentie8081** [comment]
Please provide a full list of your plugins, also we do not officially support PaperSpigot or TacoSpigot.

**Comment by flapppie1** [comment]
http://prntscr.com/eyc1bd
im running Normal spigot.

**Comment by Speentie8081** [comment]
Try it without KnockbackPatch, and see what happens

**Comment by flapppie1** [comment]
Fixed! thanks.
